account/urls.py
# from django.urls import path 
# from account.views import *

# urlpatterns = [
#     path('signup/', signup_view, name='signup'),
#     path('email/', email_view, name='email'),
#     path('forgotpassword/', forgotpassword_view, name='forgotpassword'),

# ]

from django.contrib import admin
from django.urls import path
#from django.urls import include
from . import views
from django.contrib.auth import views as authentication_views



app_name = 'account'
urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.register, name='register'),
    
    path('login/', views.userlogin, name='login'),
    #path("logout", views.userlogout, name= "logout"),
    
    # path("login/",authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', views.userlogout, name='logout'),
    
    #path("logout/",authentication_views.LogoutView.as_view(template_name='account/logout.html'),name='logout'),
    
    path('profile/', views.profile, name='profile'),
    
    path('updateprofile/', views.Editprofile, name='createprofile'),
    path("password_reset", views.password_reset_request, name="password_reset")

    
    
]

auth_wiki/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acct/', include('account.urls')),
    path('', include('library.urls')),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime


# Create your models here.

GENDER_CHOICES = (
    ('male','MALE'),
    ('female','FEMALE'),
    ('Choose not to say','CHOOSE NOT TO SAY'),
    ('Others','OTHERS'),
    ('Select Gender','SELECT GENDER')
)

class Avatar(models.Model):
    name = models.CharField(max_length=100,blank=False)
    image = models.ImageField(default='profile.jpg', upload_to='profile_pictures', null=False)

    def __str__(self):
        return self.name  


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # image = models.ForeignKey(Avatar, on_delete=models.CASCADE, related_name='avatars')
    image = models.CharField(max_length=100, blank=False, default='male.png')
    created_on = models.DateTimeField(default=datetime.now, blank=True)
    updated_on = models.DateTimeField(default=datetime.now, blank=True)
   
    
    def __str__(self):
        return self.user.username     
        

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms import ModelForm
# from . import views
from .models import *


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'focus:outline-none','placeholder':'user@gmail.com'}))
  
    class Meta:
        model=User
        fields=["username","email","password1","password2"]

    
    def save(self, commit=True):
        user=super(NewUserForm,self).save(commit=False)
        user.email= self.cleaned_data['email']
        if commit:
            user.save()
        return user
    
class ProfileForm(ModelForm):
    class Meta:
        model= Profile
        # fields=['user','image']
        fields=['user']
        
class UpdateUserForm(ModelForm):
    username = forms.CharField(max_length=100,
                               required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True,
                             widget=forms.EmailInput(attrs={'class': 'form-control'}))

    class Meta:
        model = User
        fields = ['username', 'email']


class UpdateProfileForm(ModelForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control'}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control-file'}))
   
    class Meta:
        model= Profile
        fields = '__all__'

account/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import *
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .models import Profile
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.views.decorators.csrf import csrf_exempt, csrf_protect, requires_csrf_token



# Create your views here.
def home(request):
    return render(request, 'main/index.html')

# @csrf_protect
@requires_csrf_token
def register(request):
	if request.user.is_authenticated:
		return redirect("/")
	if request.method=='POST':
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			profile = Profile(user=request.user)
			profile.save()
			return redirect('/')

		form = NewUserForm(request.POST)
		return render(request,'signup.html', context={'register_form':form, 'errors': form.errors})
            
	form = NewUserForm()
	return render(request,'signup.html', context={'register_form':form})

# @csrf_protect
@requires_csrf_token
def userlogin(request):
	if request.user.is_authenticated:
		return redirect("/")

	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.success(request, f"You are now logged in as {username}.")
				return redirect("/")
                
			else:
				return render(request, "login.html", context={"login_form":form, 'status':'error', 'alert_msg': 'User was not found try registering'})
				
		else:
			return render(request, "login.html", context={"login_form":form, 'status':'error', 'alert_msg': 'The form was invalid'})

	form = AuthenticationForm()
    
	return render(request, "login.html", context={"login_form":form})


@login_required(login_url='account:register')
def userlogout(request):
	logout(request)
	messages.info(request, "You have successfully logged out.")
	return redirect('account:login')


@login_required(login_url='account:register')
def profile(request):
    return render(request, "profile.html")   


@csrf_protect
@login_required(login_url='account:register')
def Editprofile(request):
	if request.method=='POST':
		selected_image = request.POST['image_selected']
		# new_user_name = request.POST['user_name']
		# request.user = new_user_name
		profile = get_object_or_404(Profile, user=request.user)
		profile.image = selected_image
		profile.save()
		return redirect("account:profile")
        
	return render(request,'create_profile.html')

@login_required(login_url='account:register')
def password_reset_request(request):
	if request.method == "POST":
		password_reset_form = PasswordResetForm(request.POST)
		if password_reset_form.is_valid():
			data = password_reset_form.cleaned_data['email']
			associated_users = User.objects.filter(Q(email=data))
			if associated_users.exists():
				for user in associated_users:
					subject = "Password Reset Requested"
					email_template_name = "account/password_reset_email.txt"
					c = {
					"email":user.email,
					'domain':'127.0.0.1:8000',
					'site_name': 'Website',
					"uid": urlsafe_base64_encode(force_bytes(user.pk)),
					"user": user,
					'token': default_token_generator.make_token(user),
					'protocol': 'http',
					}
					email = render_to_string(email_template_name, c)
					try:
						send_mail(subject, email, 'admin@example.com' , [user.email], fail_silently=False)
					except BadHeaderError:
						return HttpResponse('Invalid header found.')
					return redirect ("/password_reset/done/")
	password_reset_form = PasswordResetForm()
	return render(request=request, template_name="setpassword.html", context={"password_reset_form":password_reset_form})

account/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'main/img/auth_wiki_logo.png' %}" type="image/x-icon">

    <!-- css styles -->
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- bootstrap css -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous" />
    <!-- <title>Auth Wiki - Sign Up</title> -->
  </head>
  <body>
    <section>

      <nav class="navbar navbar-expand-lg un-nav py-3">
        <div class="container-fluid">
          <div class="nav-logo pl-5">
            <a class="navbar-brand ms-3" href="{% url 'home' %}"
              ><span><img src="{% static 'main/img/auth_wiki_logo.png' %}" alt="logo-head" width="40px" height="40px" /></span>
              <span class="logo-text">AUTH-WIKI</span></a
            >
          </div>
  
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mt-3 mt-lg-0 mb-lg-0 ms-lg-auto">
              <li class="nav-item active text-style">
                <a class="nav-link" href="{% url 'about' %}">About</a>
              </li>
              <li class="nav-item text-style">
                <a class="nav-link" href="{% url 'faq' %}">Faqs</a>
              </li>
              <li class="nav-item text-style">
                <a class="nav-link" href="{% url 'documentations' %}">Documentations</a>
              </li>    
              <li class="nav-item text-style">
                <a class="nav-link" href="{% url 'library' %}">Library</a>
              </li>
  
              {% if user.is_authenticated %}
  
  
                <li class="nav-item text-style d-block d-lg-none ">
                  <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
                </li>
      
                <li class="nav-item text-style d-block d-lg-none ">
                  <a class="nav-link" href="{% url 'account:logout' %}">Log Out</a>
                </li>
              
              {% endif %}
  
            </ul>
  
  
            {% if user.is_authenticated %}
   
  
            <li class="nav-item dropdown d-none d-lg-block pe-5" style='list-style-type: none'>
              <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
  
                {% if user.profile.image == 'male.png' %}
                <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
                
                {% else %}
                <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
  
                {% endif %}
                
              </a>
              <ul class="dropdown-menu" style='left: -250px; top: 60px'>
                <li>
                  <a class="dropdown-item" href="{% url 'account:profile' %}" title={{user.username}}>
                    <div class='d-flex justify-content-space-between align-items-center'>
                      {% if user.profile.image == 'male.png' %}
                      <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
                      
                      {% else %}
                      <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
        
                      {% endif %}
                      <!-- <div class='profile-circle me-3' style='padding: 15px 22px'> <strong class='text-center text-white'> {{user.username|first}} </strong> </div> -->
                      <div class='profile-content ms-3'> <strong class='d-block text-start text-black'> {{user.username}} </strong> <small  style='color: #83878A;'> {{user.email}} </small> </div>
  
                    </div>
                  </a>
                </li>
                <hr>
                <li><a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a></li>
                <hr class="dropdown-divider">
                <li><a class="dropdown-item" href="{% url 'account:createprofile' %}">Edit Profile</a></li>
                <hr class="dropdown-divider">
                <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
              </ul>
            </li>
    
            {% endif %}
            
  
            {% if not user.is_authenticated %}
  
            <div class="d-flex">
              <div class="me-4">
                <a href="{% url 'account:login' %}" class="btn btn-outline-warning un-link">
                 Sign In
                </a>
              </div>
  
              <div>
                <a href="{% url 'account:register' %}" class="btn un-link btn-warning">Sign Up</a>
              </div>
  
            {% endif %}
            </div>
          </div>
        </div>
      </nav>

      <div class="container-fluid">
        <div class="contain rounded my-5 shadow">
          <div class="row">
            {% block content %} {% endblock %}
          </div>
        </div>  
      </div>  

    </section>


  <script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
  crossorigin="anonymous"
  ></script>
  <script src = "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js" integrity="sha512-csNcFYJniKjJxRWRV1R7fvnXrycHP6qDR21mgz1ZP55xY5d+aHLfo9/FcGDQLfn2IfngbAHd8LdfsagcCqgTcQ==" crossorigin = "anonymous" referrerpolicy = "no-referrer"> </script>

</body>
</html>

account/templates/create_profile.html
{% extends 'base.html'  %} 
{% block title %} Auth Wiki - Sign Up {% endblock %}
{% load widget_tweaks %}

{% load static %}

{% block content %} 

<!-- <h2 class='text-center'> Update Profile </h2> -->


<div class="container px-4 py-4 mt-4"   >
    <!-- Account page navigation-->

    <form action='{% url "account:createprofile" %}' method='POST'>
        {% csrf_token %}
        <a href="{% url 'account:profile' %}" class="text-end d-block me-3 mb-3">Profile</a>

        <div class='row'>
            <div class='col-12 col-md-2'>
              {% if user.profile.image == 'male.png' %}
              <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='avatar' class='ms-3 border' width='100px' height='100px'> </div>
              
              {% else %}
              <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='avatar' class='ms-3 border' width='100px' height='100px'> </div>

              {% endif %}
                <!-- <img scr='{% static "img/head.png" %}' class='rounded-end d-block mx-auto' width='100px' height='100px'> -->
            </div>
            <div class='col-12 col-md-10'>

                     <!-- UserName Part -->
                    <div class="mb-4">
                        <label for='select-field d-block'> Change User Name</label>
                        <!-- <img src='{% static "img/head2.jpg" %}' > -->
                        
                        <input class="form-control w-80" type="text" name="user_name" id="" value="{{user.username}}">

                    </div>

                    <label for='select-field d-block'> Change display picture </label>
                    <!-- <img src='{% static "img/head2.jpg" %}' > -->
                    
                    <select class="form-select mt-1" name="image_selected" id='select-field' aria-label="Default select example">

                        <option selected>Choose Avatar</option>
                        <option value="male.png"> Male </option>
                        <option value="female.jpg"> Female </option>
                        <!-- <option value="3">Three</option> -->

                    </select>

                <button class='btn btn-success mt-4 mx-auto'> Change </button>


            
            
            </div>

        </div>

   


    </form>


{% endblock content %}

account/templates/email.html
{% extends 'base.html' %}
{% block title %} Auth Wiki {% endblock %}


{% block content %}


  <!-- <div class="d-flex w-100 h-100 align-items-center justify-content-center" > -->

      <div class="col-12 col-lg-6">
        <img class="main-img" src="https://wallpapercave.com/dwp1x/wp26286.jpg" alt="" >
      </div>

      <div class="col-12 col-lg-6  main-form" style="padding: 100px 50px 100px 20px;">
        <div class="shadow rounded p-5 bg-white">
          <div class="text-center">
            <h3 class="mb-4">Email instructions Sent</h3>
            <div class="py-5">
              <p>We have sent reset instructions to zuriteamparrot@gmail.com</p>
            </div>
            <p>Didn’t receive email? Click to resend</p>
          </div>
        </div>
      </div>
  <!-- </div> -->

{% endblock %}

account/templates/forgotpassword.html
{% extends 'base.html' %}
{% block title %} Auth Wiki - Sign Up {% endblock %}


{% block content %}

  <div class="col-12 col-lg-6">
    <img class="main-img" src="https://wallpapercave.com/dwp1x/wp26286.jpg" alt="">
  </div>

  <div class="col-12 col-lg-6 main-form" style="padding: 100px 50px 100px 20px;">
    <div class="border rounded p-4 w-80 d-flex justify-content-center shadow bg-white">
      <div class="w-50 text-center">
        <h3 class="mb-4">Forgot Password</h3>
        <div class="py-5">
          <p>We’ll send you reset instructions to zuriteamparrot@gmail.com</p>
        </div>
        <div class="d-grid gap-3 mb-3">
          <button class="btn btn-primary d-block" type="submit">Reset Password</button>
        </div>
      </div>
    </div>

{% endblock %}

account/templates/guidelines.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../static/css/style.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <title>Auth Wiki - Guidelines</title>
  </head>
  <body>
    <section class="vw-100 vh-100 grid">
      <div class="grid-img"></div>
      <div class="grid-form">
        <form class="border rounded p-4 w-80 d-flex justify-content-center shadow bg-white">
          <div class="w-60">
            <h3 class="text-center">Guidelines</h3>
            <p class="text-center">
              As a first time user, here are the guidelines to follow in order to enjoy the benefits
              of this product.
            </p>
            <ul class="text-left guidelines">
              <li>New users are welcome to take a product tour.</li>
              <li>As a new user, you will have to sign up to enjoy the product more.</li>
              <li>
                New users can have full access to the product provided they are auntheticated
                 users.
              </li>
              <li>Click the "I have read" option underneath the guidelines.</li>
            </ul>
            <div class="py-4 form-check">
              <input type="checkbox" class="form-check-input text-center" name="check" />
              <label class="form-check-label" for="check"
                >I have read and understood the guidelines.</label
              >
            </div>
            <div class="d-grid gap-3 mb-3">
              <button class="btn btn-primary d-block">Continue</button>
            </div>
          </div>
        </form>
      </div>
    </section>
  </body>
</html>

account/templates/login.html
{% extends 'base.html' %}
{% block title %} Auth Wiki - Sign Up {% endblock %}
{% load widget_tweaks %}

{% load static %}

{% block content %}

  {% if status == 'error' %}

  <div class="alert alert-danger" role="alert">
    {{ alert_msg }}
  </div>

  {% elif status == 'success' %}

  <div class="alert alert-success" role="alert">
    {{ alert_msg }}
  </div>

  {% endif %}

  <div class="col-12 col-lg-6 p-5">
    <img class="main-img" src="{% static 'img/person.png' %}" alt="Login Image" height="100px">
  </div>

  <div class="col-12 col-lg-6 main-form border">
    <form class="rounded p-0 w-80 d-flex justify-content-center" method="POST">
      {%csrf_token%}
      <div class="w-100 px-3 px-sm-4 py-5">
        <h2 class="text-center mb-4">Welcome Back</h2>
        <div class="mb-3">
          {{ login_form.username.label }}
          {{ login_form.username|add_class:'form-control mt-2'|attr:'type:text' }} 
        </div>
        <div class="mb-3">
          {{ login_form.password.label }}
          {{ login_form.password|add_class:'form-control mt-2'|attr:'type:password' }} 
        </div>
        <div class="mb-3 form-check d-flex justify-content-between">
          <p class="ms-auto"><a href="{% url 'account:password_reset' %}">Forgot Password?</a></p>
        </div>
        <div class="d-grid gap-3">
          <button class="btn btn-primary d-block" type="submit">Log In</button>
          <p class="text-center">Don't have an account? <a href="{% url 'account:register' %}">Create an account</a></p>
        </div>
        <!-- <div class="d-flex justify-content-between align-items-center mb-3">
          <span class="line"></span>
          <span>or</span>
          <span class="line"></span>
        </div> -->
        <div class="d-grid gap-3">
          <button class="btn btn-warning" type="button">Log In with GitHub</button>
          <button class="btn btn-warning" type="button">Log In with Google</button>
        </div>
      </div>
    </form>
  </div>

{% endblock %}

account/templates/profile.html
{% extends 'base.html'  %}
{% block title %} Profile {% endblock %}
{% load static %}
{% block content %} 

<!--<h1>This is my Profile page</h1>
<h1>{{user.username}}</h1>-->

<section style="background-color: #eee;">
    <div class="container py-5">

      <div class="row">
        <div class="col-lg-4">
          <div class="card mb-4">
            <div class="card-body text-center">

              {% if user.profile.image == 'male.png' %}
              <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='avatar' class='rounded-circle' width='150px' height='150px'> </div>
              
              {% else %}
              <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='avatar' class='rounded-circle' width='150px' height='150px'> </div>

              {% endif %}

              <!-- <img src="{% static 'img/head.png' %}" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;"> -->
              <!-- <img src="{{user.profile.image.url}}" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;"> -->
                <h5 class="my-3">{{user.username}}</h5>
                <a href="{% url 'account:createprofile'%}"><button type="button" class="btn btn-primary">Update Profile</button></a>
            </div>
            </div>
        </div>
        <div class="col-lg-8">
          <div class="card mb-4">
            <div class="card-body">
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">User Name</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.username}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Email</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.email}}</p>
                </div>
              </div>
              <hr>
              <div class="row">
                <div class="col-sm-3">
                  <p class="mb-0">Joined On</p>
                </div>
                <div class="col-sm-9">
                  <p class="text-muted mb-0">{{user.profile.created_on}}</p>
                </div>
              </div>
            </div>
          </div>

{% endblock content %}

account/templates/resetsuccessful.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="../styles/style.css" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />
    <title>Auth Wiki - Reset Successful</title>
  </head>
  <body>
    <section class="vw-100 vh-100 grid">
      <div class="grid-img"></div>
      <div class="grid-form">
        <form class="border rounded p-4 w-80 d-flex justify-content-center shadow bg-white">
          <div class="w-60">
            <p class="text-center py-5">Password reset successful!</p>
            <div class="d-grid gap-3 mb-3">
              <button class="btn btn-primary d-block" type="submit">Reset Password</button>
            </div>
          </div>
        </form>
      </div>
    </section>
  </body>
</html>

account/templates/setpassword.html
{% extends 'base.html' %}
{% block title %} Auth Wiki - Sign Up {% endblock %}
{% load widget_tweaks %}

{% block content %}
  <div class="col-12 col-lg-6">
    <img class="main-img" src="https://wallpapercave.com/dwp1x/wp26286.jpg" alt="">
  </div>

  <div class="col-12 col-lg-6 main-form">
    <form class="rounded p-0 w-80 d-flex justify-content-center">
      <div class="w-100 px-3 px-sm-4 py-5">
        <h2 class="text-center mb-4">Set New Password</h2>
        <p class="text-center">
          Your new password must be different from the previously used passwords.
        </p>
        <div class="mb-3">
          <label for="password" class="form-label">Password</label>
          <input type="password" class="form-control" name="password" />
        </div>
        <div class="mb-3">
          <label for="password" class="form-label">Confirm Password</label>
          <input type="password" class="form-control" name="password" />
        </div>
        <div class="d-grid gap-3 mb-3">
          <button class="btn btn-primary d-block" type="submit">Reset Password</button>
        </div>
      </div>
    </form>
  </div>
{% endblock %}

account/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Auth Wiki - Sign Up {% endblock %}
{% load widget_tweaks %}

{% block content %}
  <div class="col-12 col-lg-6 p-5">
    <img class="main-img" src="{% static 'img/person.png' %}" alt="Register image" height="100px">
  </div>
  <div class="col-12 col-lg-6 main-form border">
    <form class="rounded p-0 w-80 d-flex justify-content-center" method="POST">
      <div class="px-3 px-sm-1 py-5">
        <h3 class="text-center mb-4">Create Account</h3>

        {% if register_form.errors %}
        {% for field in register_form %}

            {% for error in field.errors %}
              <div class="text-danger mb-3">
                {{field.label}}: {{ error|escape }}

              </div>
            {% endfor %}

        {% endfor %}
      {% endif %}

        
   

        {% csrf_token %}
        <!-- <button class="btn btn-primary" type="submit">Register</button> -->

        <div class="mb-3">  
          {{ register_form.username.label }}
          {{ register_form.username|add_class:'form-control mt-2'|attr:'type:text' }} 
        </div>

        <div class="mb-3">
          {{ register_form.email.label }}
          {{ register_form.email|add_class:'form-control mt-2'|attr:'type:email' }}
        </div>
        <div class="mb-3">
          {{ register_form.password1.label }}
          {{ register_form.password1|add_class:'form-control mt-2'|attr:'type:password' }}

        </div>
        <div class="mb-3">
          {{ register_form.password2.label }}
          <!-- {{ register_form }} -->
          {{ register_form.password2|add_class:'form-control mt-2'|attr:'type:password' }}
        </div>
        <div class="mb-2 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1" />
          <label class="form-check-label" for="check"
            >I have reviewed and accepted the privacy policy and terms of service.</label
          >
        </div>
        <div class="d-grid gap-3">
          <button class="btn btn-primary d-block" type="submit">Create Account</button>
          <p class="text-center">Already have an account? <a href="{% url 'account:login' %}"> Sign In </a> </p>
        </div>
        <div class="d-flex justify-content-between align-items-center mb-3">
          <span class="line"></span>
          <span>or</span>
          <span class="line"></span>
        </div>
        <div class="d-grid gap-3">
          <button class="btn btn-warning" type="button">Sign up with GitHub</button>
          <button class="btn btn-warning" type="button">Sign up with Google</button>
        </div>
      </div>
    </form>
  </div>



{% endblock %}