account/urls.py
# from django.urls import path 
# from account.views import *

# urlpatterns = [
#     path('signup/', signup_view, name='signup'),
#     path('email/', email_view, name='email'),
#     path('forgotpassword/', forgotpassword_view, name='forgotpassword'),

# ]

from django.contrib import admin
from django.urls import path
#from django.urls import include
from . import views
from django.contrib.auth import views as authentication_views



app_name = 'account'
urlpatterns = [
    path('', views.home, name='home'),
    path('register/',views.register, name='register'),
    
    path('login/', views.userlogin, name='login'),
    #path("logout", views.userlogout, name= "logout"),
    
    # path("login/",authentication_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/', views.userlogout, name='logout'),
    
    #path("logout/",authentication_views.LogoutView.as_view(template_name='account/logout.html'),name='logout'),
    
    path('profile/', views.profile, name='profile'),
    
    path('updateprofile/', views.Editprofile, name='createprofile'),
    path("password_reset", views.password_reset_request, name="password_reset")

    
    
]

auth_wiki/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('acct/', include('account.urls')),
    path('', include('library.urls')),
    path('api_auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

library/urls.py
from django.urls import path 
from library.views import *

urlpatterns = [
    path('', home_view, name='home'),
    path('about/', about_view, name='about'),
    path('faq/', faq_view, name='faq'),
    path('documentations/', documentation_view, name='documentations'),
    path('library/', library_view, name='library'),
    path('library/<slug>/', detail_view, name='details'),
    path('search/', search_library, name='search'),
    path("<int:pk>/create_comment", CommentAPIView.as_view(), name="create-comment"),
    path("comment/<int:pk>/create_upvote", UpVoteAPIView.as_view(), name="create-upvote"),
    path("comment/<int:pk>/create_downvote", DownVoteAPIView.as_view(), name="create-downvote")
]

library/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
from django.conf import settings
from datetime import datetime
from account.models import *

# Create your models here.

class Post(models.Model):
    title = models.TextField(max_length=500)
    description = models.TextField(max_length=700)
    slug = models.SlugField(unique=True, db_index=True, null=True)
    code_snippet = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    likes= models.ManyToManyField(User, blank=True, related_name='likes')
    dislikes= models.ManyToManyField(User, blank=True, related_name='dislikes')
    numberofdownloads = models.IntegerField(default=0)
    github = models.URLField(max_length=500, null=True, blank=True,)
    download = models.URLField(max_length=500, null=True, blank=True,)
    images = models.ImageField(upload_to='library_images', blank=True)

    def __str__(self):
        return f'{self.title} <--> {self.author}'

class Category(models.Model):
    name = models.CharField(max_length=200, default="Auth Lib")

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {0} by {1}'.format(self.content, self.user)


class UpVote(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="upvote_user"
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)

    def __str__(self):
        return str(self.user)


class DownVote(models.Model):
    comment = models.ForeignKey(
        Comment, on_delete=models.CASCADE, related_name="downvote_user"
    )
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,)

    def __str__(self):
        return str(self.user)


class Faq(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

class Documentation(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()

    def __str__(self):
        return self.title

GENDER_CHOICES = (
    ('male.png','MALE'),
    ('female.jpg','FEMALE'),
    # ('Choose not to say','CHOOSE NOT TO SAY'),
    # ('Others','OTHERS'),
    # ('Select Gender','SELECT GENDER')
)


class Team(models.Model):
    name = models.CharField(max_length=100)
    role = models.CharField(max_length=100)
    image_choice = models.CharField(max_length=30, choices=GENDER_CHOICES, default='Select Gender')

    def __str__(self):
        return self.name
    

library/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

library/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from .forms import *
from .serializers import *
from django.http import HttpResponseRedirect
from django.urls import reverse
from rest_framework import generics
from rest_framework.authentication import TokenAuthentication
from rest_framework.exceptions import ValidationError
from rest_framework.permissions import IsAdminUser, IsAuthenticated
from django.contrib.auth.decorators import login_required
from django.db.models.query_utils import Q


# Create your views here.
def home_view(request):
    template_name = 'main/index.html'
    data = Post.objects.all().order_by('-category')
    context = {'post_data':data[:4]}
    return render(request, template_name, context)

def about_view(request):
    template_name = 'main/about.html'
    data = Team.objects.all()
    context = {'about_data':data}

    return render(request, template_name, context=context)

def faq_view(request):
    template_name = 'main/faq.html'
    data = Faq.objects.all()
    context = {
        'faq_data': data,
    }

    return render(request, template_name, context=context)


def library_view(request):
    template_name = 'main/library.html'
    data = Post.objects.all()
    context = {'post_data':data}
    return render(request, template_name, context=context)


def documentation_view(request):
    template_name = 'main/documentation.html'
    context = {}
    return render(request, template_name, context=context)



@login_required(login_url='account:register')
def detail_view(request, slug):
    template_name = 'main/details_page.html'
    requested_post = get_object_or_404(Post, slug=slug)
    comments = requested_post.comments.all().order_by('-created_on')
    form = CommentForm()
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = requested_post
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse('details', args=[slug]))



    context = {
        'detail_post': requested_post,
        'comments_data': comments,
        'comment_form': form,
    }

    return render(request, template_name, context)

def search_library(request):
    search_q = request.GET.get('q')
    filtered_object = Post.objects.filter(Q(title__contains=search_q) | Q(description__contains=search_q))
    context = {
        'post_data': filtered_object,
        'length_of_data': len(filtered_object),
        'searched_q': search_q,
    }
    return render(request, 'main/search.html', context)



# Create your views here.
class DownVoteAPIView(generics.CreateAPIView):
    serializer_class = DownVoteSerializer
    queryset = DownVote.objects.all()
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        pk = self.kwargs["pk"]
        comment = Comment.objects.get(pk=pk)
        review_user = self.request.user
        upvote_queryset = UpVote.objects.filter(comment=comment, user=review_user)
        downvote_queryset = DownVote.objects.filter(comment=comment, user=review_user)
        if downvote_queryset.exists():
            raise ValidationError("Comment already downvoted by you")
        if upvote_queryset.exists():
            upvote_queryset.delete()
        serializer.save(comment=comment, user=review_user,)


class UpVoteAPIView(generics.CreateAPIView):
    serializer_class = UpVoteSerializer
    queryset = UpVote.objects.all()
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]

    def perform_create(self, serializer):
        pk = self.kwargs["pk"]
        comment = Comment.objects.get(pk=pk)
        review_user = self.request.user
        upvote_queryset = UpVote.objects.filter(comment=comment, user=review_user)
        downvote_queryset = DownVote.objects.filter(comment=comment, user=review_user)
        if upvote_queryset.exists():
            raise ValidationError("Comment already upvoted by you")
        if downvote_queryset.exists():
            downvote_queryset.delete()
        serializer.save(comment=comment, user=review_user,)


class CommentAPIView(generics.ListCreateAPIView):
    serializer_class = CommentSerializer
    authentication_classes = [TokenAuthentication]
    permission_classes = [IsAuthenticated]
    queryset = Comment.objects.all()

    def get_object(self):
        return Comment.objects.all()

    def perform_create(self, serializer):
        pk = self.kwargs["pk"]
        post = Post.objects.get(pk=pk)
        user = self.request.user
        serializer.save(**self.request.data, user=user, post=post)

library/templates/main/about.html
{% extends 'main/base.html' %}

{% block page_title %} About {% endblock %}
{% load static %}

{% block content %}

<main class="container">
  <div class="pt-3">
    <h1 class="text-center">About us</h1>
    <div class="my-5">
      <p>
        Auth-Wiki is a library authentication application that allow users to create different
        authentication code samples and interact. Users can easily access/download our code
        samples or able to view example usage.
      </p>
      <p>
        The users can make use of the library code when creating an authentication code or when
        browsing through the library.
      </p>
      <p>
        At AuthWiki, guests are not also left out as they can easily view, interact with the
        documentation and register to contribute.
      </p>
      <p>
        Though, one of the cons of being a guest is the inability to download code while on the
        other hand, the registered users have full access, can interact easily, make
        contributions, able to view example usage and download  code samples.
      </p>
    </div>
    <h3 class="text-center">Meet Our Amazing Team</h3>
    <div class="mt-5">

      <div class="team">
      {% for data in about_data %}

        <div class="d-flex flex-column align-items-center mb-5">

          <div class="mb-3">

            {% if data.image_choice == 'male.png' %}
            <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
            
            {% else %}
            <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>

            {% endif %}
          </div>


          <span>{{data.name}}</span>
          <b>{{data.role}}</b>
        </div>

        {% endfor %}
      
      </div>


    </div>
  </div>
</main>

{% endblock %}

library/templates/main/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'main/img/auth_wiki_logo.png' %}" type="image/x-icon">

    <!-- css styles -->
    <link rel="stylesheet" href="{% static 'main/css/styles.css' %}" />

    <!-- Bootstrap CSS -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />

    <!-- Bootstrap icon -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css" integrity="sha384-xeJqLiuOvjUBq3iGOjvSQSIlwrpqjSHXpduPd6rQpuiM3f5/ijby8pCsnbu5S81n" crossorigin="anonymous">


    <title> {% block page_title %} {% endblock %} </title>
  </head>

  <body class="pt-5">
    <!-- note: this page is for unauthenticated users -->
    <!-- navbar -->



    <nav class="navbar navbar-expand-lg fixed-top un-nav py-3">
      <div class="container-fluid">
        <div class="nav-logo pl-5">
          <a class="navbar-brand ms-3" href="{% url 'home' %}"
            ><span><img src="{% static 'main/img/auth_wiki_logo.png' %}" alt="logo-head" width="40px" height="40px" /></span>
            <span class="logo-text">AUTH-WIKI</span></a
          >
        </div>

        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mt-3 mt-lg-0 mb-lg-0 ms-lg-auto">
            <li class="nav-item active text-style">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            <li class="nav-item text-style">
              <a class="nav-link" href="{% url 'faq' %}">Faqs</a>
            </li>
            <li class="nav-item text-style">
              <a class="nav-link" href="{% url 'documentations' %}">Documentations</a>
            </li>    
            <li class="nav-item text-style">
              <a class="nav-link" href="{% url 'library' %}">Library</a>
            </li>

            {% if user.is_authenticated %}


              <li class="nav-item text-style d-block d-lg-none ">
                <a class="nav-link" href="{% url 'account:profile' %}">Profile</a>
              </li>
    
              <li class="nav-item text-style d-block d-lg-none ">
                <a class="nav-link" href="{% url 'account:logout' %}">Log Out</a>
              </li>
            
            {% endif %}

          </ul>


          {% if user.is_authenticated %}
 

          <li class="nav-item dropdown d-none d-lg-block pe-5" style='list-style-type: none'>
            <a class="nav-link" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">

              {% if user.profile.image == 'male.png' %}
              <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
              
              {% else %}
              <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>

              {% endif %}
              
            </a>
            <ul class="dropdown-menu" style='left: -250px; top: 60px'>
              <li>
                <a class="dropdown-item" href="{% url 'account:profile' %}" title={{user.username}}>
                  <div class='d-flex justify-content-space-between align-items-center'>
                    {% if user.profile.image == 'male.png' %}
                    <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
                    
                    {% else %}
                    <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='not found' class='rounded-circle' width='50px' height='50px'> </div>
      
                    {% endif %}
                    <!-- <div class='profile-circle me-3' style='padding: 15px 22px'> <strong class='text-center text-white'> {{user.username|first}} </strong> </div> -->
                    <div class='profile-content ms-3'> <strong class='d-block text-start text-black'> {{user.username}} </strong> <small  style='color: #83878A;'> {{user.email}} </small> </div>

                  </div>
                </a>
              </li>
              <hr>
              <li><a class="dropdown-item" href="{% url 'account:profile' %}">Profile</a></li>
              <hr class="dropdown-divider">
              <li><a class="dropdown-item" href="{% url 'account:createprofile' %}">Edit Profile</a></li>
              <hr class="dropdown-divider">
              <li><a class="dropdown-item" href="{% url 'account:logout' %}">Logout</a></li>
            </ul>
          </li>
  
          {% endif %}
          

          {% if not user.is_authenticated %}

          <div class="d-flex">
            <div class="me-4">
              <a href="{% url 'account:login' %}" class="btn btn-outline-warning un-link">
               Sign In
              </a>
            </div>

            <div>
              <a href="{% url 'account:register' %}" class="btn un-link btn-warning">Sign Up</a>
            </div>

          {% endif %}
          </div>
        </div>
      </div>
    </nav>

  

    <div class="mt-5">
    {% block content %}

    {% endblock %}
   </div>

    <footer class="d-block" style='position: relative; bottom:0; margin-top:100px;'>
        <div class="bg-light-grey py-2">
            <div class="d-flex justify-content-center align-items-center container">
                <p class="mt-2">&copy; 2022 Zuri Team Parrot</p>
            </div>
        </div>
    </footer>
    <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
    crossorigin="anonymous"
    ></script>
    <script src = "https://cdnjs.cloudflare.com/ajax/libs/FileSaver.js/2.0.0/FileSaver.min.js" integrity="sha512-csNcFYJniKjJxRWRV1R7fvnXrycHP6qDR21mgz1ZP55xY5d+aHLfo9/FcGDQLfn2IfngbAHd8LdfsagcCqgTcQ==" crossorigin = "anonymous" referrerpolicy = "no-referrer"> </script>

    </body>
</html>

library/templates/main/details_page.html
{% extends 'main/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block page_title %} Library {% endblock %}



{% block content %}
    <div class='container'>

        <h1 class='post-title pt-3'> {{detail_post.title}} </h1>

        <div class='post-description py-3'>
            {{detail_post.description}}
        </div>

        <div class='code_snippet_box mt-5'>
            <div class='code_snippet bg-dark'>

                <div class='d-flex justify-content-between align-items-center mb-3'>
                    <strong> Code Snippet </strong>
                    <div class='copy_btn d-block' onclick=copy()> <i class="bi bi-clipboard"></i>  </div>
                </div>
                <script>
                    function copy(){
                        text = document.getElementsByClassName('snippet_code')[0].innerHTML;

                        navigator.clipboard.writeText(text);
                        alert('Code Copied.')
                    }
                </script>

                <span class='snippet_code' style='display:none'> {{detail_post.code_snippet}} </span>
                <span class='snippet_code_br'> {{detail_post.code_snippet|linebreaksbr}} </span>
            </div>

            <div class='post_buttons d-flex justify-content-between flex-column flex-md-row align-items-center mt-3' style='padding:0 20%;'>
                <button class='btn btn-primary text-light'> <a href='{{detail_post.github}}' class='text-white' target='_blank'> <i class="bi bi-github"></i> Github Repo </a>  </button>

                <!-- <div class='like-dislike-div shadow'>

                </div> -->

                <div class="btn-group" role="group" aria-label="Basic example">
                    <button type="button" class="btn btn-success"><i class="bi bi-hand-thumbs-up fs-5 px-2 "></i></button>
                    <button type="button" class="btn btn-success"><i class="bi bi-hand-thumbs-down fs-5 px-2"></i></button>
                  </div>

                <button class='btn btn-primary py-2' data-bs-toggle="modal" data-bs-target="#staticBackdrop"> <i class="bi bi-download"></i> Download  </button>
            </div>

            <!-- Modal for download btn -->
                <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                        
                        <div class="modal-body p-5">
                            <h4 class='text-center mb-5'> Continue Download </h4>
                            <div class=''>
                                <button type="button" class="btn btn-primary px-5 me-5" onclick='saveStaticDataToFile()' data-bs-dismiss="modal">Yes</button>
                                <script>
                                        function saveStaticDataToFile() {
                                            var content = document.getElementsByClassName('snippet_code')[0].innerHTML
                                            var title = document.getElementsByClassName('post-title')[0].innerHTML
                                            var blob = new Blob([content], 
                                                { type: "text/plain;charset=utf-8" });
                                            saveAs(blob, `${title}-auth-wiki.txt`);
                                        }
                                </script>
                                <button type="button" class="btn btn-warning px-5 ms-5" data-bs-dismiss="modal">No</button>
                            </div>
                            

                        </div>
                        <!-- <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary">Understood</button>
                        </div> -->
                    </div>
                    </div>
                </div>

        </div>
        
         <br>

        <div class='my-5'> 

            <h6> Comment on this post: </h6>
            <form id='comment_form' action='{% url "details" detail_post.slug %}' method='POST'>
                {% csrf_token %}
                <div class='mt-5'>

                    <div>
                        {{ comment_form.content|add_class:'px-3 pt-3 w-100'|attr:'cols:80'|attr:'rows:5'|attr:'placeholder:Drop a comment!' }}
                    </div>
                </div>
                
                <div class='text-end'> <button class="btn btn-dark"> Save Comment </button> </div>
            </form>
        </div>

        {% if comments_data.exists %}
        <h6 class='mt-5'> Comments: </h6>
        {% endif %}
        <div class='pple_comment_container'> 

            {% for data in comments_data %}
            <div class='pple_comment_box border p-4'> 
                <div class='first-row d-flex flex-direction-row'>
                    
                    {% if user.profile.image == 'male.png' %}
                    <div> <img src=' {% static "img/"|add:"male.png" %} ' alt='avatar' class='rounded-circle' width='50px' height='50px'> </div>
                    
                    {% else %}
                    <div> <img src=' {% static "img/"|add:"female.jpg" %} ' alt='avatar' class='rounded-circle' width='50px' height='50px'> </div>
      
                    {% endif %}
                    <!-- {% if data.user.profile.first_name %}
                    <img scr='{{data.user.profile.image.url}}' alt='' class='rounded-circle d-block' width='50px' height='50px'>
                    {% else %}
                    <div class='profile-circle' style='padding: 15px 22px; width:50px; height:50px'> <strong class='text-center text-white'> {{data.user.username|first}} </strong> </div>
                    {% endif %} -->

                    <div class='ms-3 mt-1'>
                        <strong class='d-block'>  {{ data.user.username|capfirst }} </strong>
                        <small class='text-muted text-end d-block'> {{ data.created_on }} </small>

                    </div>
                
                </div>

                <div class='second-row mt-4'>
                    <p> {{ data.content }} </p>
                </div>
    
            </div>
       
            {% endfor %}

        </div>
    

    </div>

    <!-- <button> Like </button> <br>
    <button> Disike </button>
     -->



{% endblock %}

library/templates/main/faq.html
{% extends 'main/base.html' %}
{% load static %}
{% block page_title %} FAQ {% endblock %}

{% block content %}

<main>
  <div class="container pt-3">
    <div>
      <h3 class="text-center pb-3 pt-3">FAQs</h3>

  <div class="accordion accordion-flush mb-5" id="accordionFlushExample">

    {% for data in faq_data %}
      <div class="accordion-item">
        <h2 class="accordion-header" id="panelsStayOpen-heading-{{data.id}}">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapse-{{data.id}}" aria-expanded="true" aria-controls="panelsStayOpen-collapse-{{data.id}}">
            {{ data.title }}
          </button>
        </h2>
        <div id="panelsStayOpen-collapse-{{data.id}}" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-heading-{{data.id}}">
          <div class="accordion-body">
            <p> {{ data.content }} </p>
          </div>
        </div>
      </div>
    {% endfor %}
  

  <!-- <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingTwo">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">
        Do I need to use the AuthWiki application?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingTwo">
      <div class="accordion-body">
        <p>Yes, if you're interested in building an application. It is effective and has easy
          access for auntheticated users. </p>
      </div>
    </div>
  </div>
  <div class="accordion-item">
    <h2 class="accordion-header" id="panelsStayOpen-headingThree">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">
        How does AuthWiki help users to make documentation?
      </button>
    </h2>
    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse" aria-labelledby="panelsStayOpen-headingThree">
      <div class="accordion-body">
        <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
      </div>
    </div>
  </div> -->
</div>

</main>

{% endblock %}

library/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block page_title %} Home {% endblock %}

{% block content %}
<!-- header section -->
<header class="container-fluid">
  <div class="row mb-4 px-3">
    <!-- header image -->
    <div class="col-12 col-lg-5">
      <img class="w-100 mx-auto" src="{% static 'main/img/community-removebg-preview.png' %}" alt="img"  height="450px" />
    </div>
    <!-- header community -->
    <div class="col-12 col-lg-7 d-flex flex-column justify-content-center align-items-center">
      <h1 class="text-primary text-start font-weight-bold">Join our community!</h1>
      <p class="w-75 my-3 my-md-4">
        We welcome you to be part of our ever-growing community! AuthWiki is a platform that
        allow authenticated users have full access to the platform, view and interact with the
        documentation. They can also register to make contributions by making comments and
        reactions. Users that have authenticated access can browse through the library, view and
        download code samples.
      </p>

      <a href="{% url 'library' %}" class="btn btn-primary" role="button">Browse full library</a>
    </div>
  </div>
</header>

<!-- search for code section -->
<!-- <section class="search-code container-fluid d-flex justify-content-center align-items-center py-5"> -->

    <div class="text-center py-5">
      <h3 class="font-bold">Search For Codes</h3>
      <form class="container-fluid d-flex justify-content-center" action='{% url "search" %}' method='GET'>
        {% csrf_token %}
        <div class="w-30">
          <input class="form-control me-2" type="search" name="q" placeholder="Search" aria-label="Search">
        </div>

        <button class='btn btn-dark'>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16"> <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z"/></svg>  
        </button> 
      </form>
    </div>

<!-- search codes items -->
<div class="container">
  <!-- .search-code items -->
  <div class="search-code__items">
    <div class="grid gap-5">
      {% for data in post_data %}
      <a href='{% url "details" data.slug %}'>

        <div class="w-100 search-code__card shadow-sm">
          <div class="d-flex flex-column p-4 box">
            <div>
              <h5>{{data.title}}</h5>
              <p class="text-wrap w-75 text-grey">
                {{data.description | truncatewords:20}}
              </p>
            </div>

            <div class="font-bold  text-muted">
              <span><i class="bi bi-download"></i> {{data.numberofdownloads}} downloads </span>
            </div>
          </div>
        </div>
      </a>
      {% endfor %}
    </div>
  </div>
</div> 

{% endblock %}